#pragma once

#define dfPACKET_SC_CREATE_MY_CHARACTER 0
#define dfPACKET_SC_CREATE_OTHER_CHARACTER 1
#define dfPACKET_SC_DELETE_CHARACTER 2
#define dfPACKET_CS_MOVE_START 10
#define dfPACKET_SC_MOVE_START 11
#define dfPACKET_CS_MOVE_STOP 12
#define dfPACKET_SC_MOVE_STOP 13
#define dfPACKET_CS_ATTACK1 20
#define dfPACKET_SC_ATTACK1 21
#define dfPACKET_CS_ATTACK2 22
#define dfPACKET_SC_ATTACK2 23
#define dfPACKET_CS_ATTACK3 24
#define dfPACKET_SC_ATTACK3 25
#define dfPACKET_SC_DAMAGE 30

enum class PACKET_TYPE : BYTE
{
   SC_CREATE_MY_CHARACTER = 0,
   SC_CREATE_OTHER_CHARACTER = 1,
   SC_DELETE_CHARACTER = 2,

   CS_MOVE_START = 10,
   SC_MOVE_START = 11,
   CS_MOVE_STOP = 12,
   SC_MOVE_STOP = 13,

   CS_ATTACK1 = 20,
   SC_ATTACK1 = 21,
   CS_ATTACK2 = 22,
   SC_ATTACK2 = 23,
   CS_ATTACK3 = 24,
   SC_ATTACK3 = 25,

   SC_DAMAGE = 30,

   END
};
